name: Update Release Information

on:
  release:
    types: [published]

jobs:
  update_release_information:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Release Information
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github } = require('@actions/github');
            const { owner, repo } = github.context.repo;
            const { release } = github.context.payload;

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { data: existingRelease } = await octokit.repos.getReleaseByTag({
              owner,
              repo,
              tag: release.tag_name
            });

            await octokit.repos.updateRelease({
              owner,
              repo,
              release_id: existingRelease.id,
              name: release.tag_name,
              body: 'Your updated release description goes here.'
            });
