name: Update Release Information

on:
  release:
    types: [published]

jobs:
  update_release_information:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Release Information
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: `${{ github.event.release.id }}`,
              name: 'Haha',
              body: 'hello owrld.'
            });
